### ISSUE TITLE
noVNC encountered an error:  Uncaught TypeError: crypto.randomUUID is not a function chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/injectedScript.bundle.js:2:90761

### ISSUE THREAD

**Issue by skirsch** [accetto/debian-vnc-xfce-g3#1]
doing reload when connected to full VNC generates this error message. Oddly, if I connect to the root of noVNC, I can select the Full version just fine. Just happens on reload (I'm using Chrome browser on windows).

This may not be your bug or something you can fix, but I've never seen this before.

```
noVNC encountered an error:

Uncaught TypeError: crypto.randomUUID is not a function
chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/injectedScript.bundle.js:2:90761
```

![image](https://github.com/user-attachments/assets/e7ffc1a4-2c68-46da-b68e-7a1ced4607d1)

GREAT work.

Have you thought of including a docker compose.yaml file for sample usage in the readme?

```
version: "3.8"
### listens on 5901 for VNC connections and 
### 6901 for NoVNC web connection
### so point the web browser to 8084 and enter 
### the password: x
### when you get in, the sudo password is headless
services:
  debian:
    image: accetto/debian-vnc-xfce-chromium-g3
    hostname: debian
    restart: unless-stopped
    ports:
      - 8084:6901
    shm_size: 512m ## container run time
    environment:
      VNC_PW: x
      VNC_RESOLUTION: 1920x1080
    volumes:
      - /mnt/main/appdata/Debian-Bullseye:/mnt/debian
networks: {}
```
